#!/usr/bin/env python
"""Build the Call Analysis Windows desktop app (Python backend + Electron shell).

Pipeline:
  1. Generate app icon (electron/assets/icon.ico).
  2. Install Python deps (editable) if missing.
  3. Build the backend with PyInstaller -> dist/backend/CallAnalysisBackend/.
  4. npm install in electron/ (skipped with --skip-npm).
  5. electron-builder --win nsis -> dist/desktop/CallAnalysis-Setup-<ver>.exe

Usage:
    python build_electron.py              # full build
    python build_electron.py --skip-backend   # reuse an existing backend build
    python build_electron.py --skip-npm       # reuse existing node_modules
    python build_electron.py --dir            # unpacked dir (no installer)
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
ELECTRON_DIR = PROJECT_ROOT / "electron"
BACKEND_OUT = PROJECT_ROOT / "dist" / "backend" / "CallAnalysisBackend"


def run(cmd: list[str], cwd: Path | None = None) -> int:
    print(f"\n==> {' '.join(cmd)}", flush=True)
    return subprocess.run(cmd, cwd=cwd).returncode


def force_rmtree(path: Path) -> None:
    """Remove a directory tree on Windows, resetting read-only bits if needed."""
    import os
    import stat

    def _on_error(func, path_str, exc_info):
        # Make read-only files writable then retry
        os.chmod(path_str, stat.S_IWRITE)
        func(path_str)

    if path.exists():
        print(f"    Removing {path}", flush=True)
        shutil.rmtree(path, onerror=_on_error)


def build_icon() -> None:
    print("\n==> Generating app icon", flush=True)
    icon_py = PROJECT_ROOT / "tools" / "make_icon.py"
    if not icon_py.exists():
        print("    tools/make_icon.py missing — skipping icon generation")
        return
    run([sys.executable, str(icon_py)])


def build_backend() -> int:
    """PyInstaller onedir build of the API server (console exe, hidden by Electron)."""
    print("\n==> Building Python backend with PyInstaller", flush=True)

    if run([sys.executable, "-m", "pip", "install", "-q", "pyinstaller", "-e", "."]) != 0:
        return 1

    spec = PROJECT_ROOT / "CallAnalysisBackend.spec"
    src_dir = PROJECT_ROOT / "src"
    web_src = src_dir / "call_analysis" / "web"
    alembic_src = src_dir / "call_analysis" / "alembic"
    datas = [f"('{web_src.as_posix()}', 'call_analysis/web')"]
    if alembic_src.is_dir():
        datas.append(f"('{alembic_src.as_posix()}', 'call_analysis/alembic')")

    spec.write_text(
        f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_electron.py — backend for the desktop app.

block_cipher = None

from PyInstaller.utils.hooks import collect_submodules

a = Analysis(
    ['{ (src_dir / 'call_analysis' / 'serve.py').as_posix() }'],
    pathex=['{src_dir.as_posix()}', '{PROJECT_ROOT.as_posix()}'],
    binaries=[],
    datas=[{', '.join(datas)}],
    hiddenimports=[
        # uvicorn loads the app via the string "call_analysis.api.app:app", so
        # PyInstaller never sees these as imports — pull in the whole package.
        *collect_submodules('call_analysis'),
        'sqlalchemy.dialects.postgresql',
        'celery.loaders.default',
        'opentelemetry.instrumentation.fastapi',
        'opentelemetry.instrumentation.sqlalchemy',
        'opentelemetry.instrumentation.redis',
        'opentelemetry.instrumentation.httpx',
        'prometheus_client',
        'structlog',
        'passlib.handlers.bcrypt',
        'jose.backends.rsa_backend',
        'faster_whisper',
        'ctranslate2',
        'numpy',
        'librosa',
        'av',
        'soundfile',
        'onnxruntime',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['pytest', 'mkdocs', 'sphinx', 'black', 'ruff', 'mypy', 'testcontainers'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CallAnalysisBackend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Electron hides the console via windowsHide
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CallAnalysisBackend',
)
""",
        encoding="utf-8",
    )

    # Pre-create work/dist dirs — on Windows, --clean removes them and
    # PyInstaller sometimes fails to recreate before writing base_library.zip.
    work_dir = PROJECT_ROOT / "build" / "CallAnalysisBackend"
    dist_dir = PROJECT_ROOT / "dist"

    # Force-remove any stale output from a previous build; PyInstaller's own
    # rmtree fails on Windows when files are still locked by Explorer/AV.
    force_rmtree(work_dir)
    force_rmtree(dist_dir / "CallAnalysisBackend")

    work_dir.mkdir(parents=True, exist_ok=True)
    dist_dir.mkdir(parents=True, exist_ok=True)

    if run([
        "pyinstaller", "--clean", "--noconfirm",
        "--workpath", str(work_dir),
        "--distpath", str(dist_dir),
        str(spec),
    ]) != 0:
        return 1

    # PyInstaller writes to build/CallAnalysisBackend + dist/CallAnalysisBackend
    built = PROJECT_ROOT / "dist" / "CallAnalysisBackend"
    if not built.is_dir():
        print("!! PyInstaller output not found — expected dist/CallAnalysisBackend/")
        return 1

    if BACKEND_OUT.exists():
        force_rmtree(BACKEND_OUT)
    BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(built, BACKEND_OUT)
    print(f"    Backend ready at {BACKEND_OUT}")
    return 0


def build_desktop(skip_npm: bool, dir_only: bool) -> int:
    print("\n==> Building Electron app", flush=True)
    pkg = ELECTRON_DIR / "package.json"
    if not pkg.exists():
        print("!! electron/package.json missing")
        return 1

    if not skip_npm:
        if run(["npm", "install"], cwd=ELECTRON_DIR) != 0:
            return 1

    target = "--dir" if dir_only else "--win"
    npx = shutil.which("npx") or "npx"
    rc = run([npx, "electron-builder", target, "--config", str(ELECTRON_DIR / "package.json")], cwd=ELECTRON_DIR)
    if rc == 0:
        out = PROJECT_ROOT / "dist" / "desktop"
        print(f"\nBuild complete! Installer(s) in: {out}")
    return rc


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Call Analysis desktop app")
    parser.add_argument("--skip-backend", action="store_true", help="Reuse existing dist/backend build")
    parser.add_argument("--skip-npm", action="store_true", help="Reuse existing electron/node_modules")
    parser.add_argument("--dir", action="store_true", help="Unpacked directory instead of NSIS installer")
    args = parser.parse_args()

    build_icon()

    if not args.skip_backend:
        if build_backend() != 0:
            return 1
    else:
        print("\n==> Skipping backend build (--skip-backend)")

    return build_desktop(args.skip_npm, args.dir)


if __name__ == "__main__":
    sys.exit(main())
